"use client"

import Head from "next/head";
import Masonry from "react-masonry-css";
import Image from "next/image";

import { dic, pics } from "../_images";

export default function Page() {

  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="relative pt-[110px] z-20">
        <div className="text-center uppercase text-3xl">Gallery</div>

        <div className="flex flex-col h-full items-center">
          <Masonry breakpointCols={2} className="flex gap-4 h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
            {pics.map((key) => (
              <div key={key + "wrapper"} className="relative">
                <Image
                  key={key}
                  src={dic[key][0]}
                  alt="thumbnail"
                  className="my-4 cursor-pointer"
                  placeholder="blur"
                />
                <a key={key + "link"} href={"/gallery/" + key} className="absolute inset-0 bg-stone-900 opacity-0 hover:opacity-40
                items-center justify-center flex text-xl uppercase duration-300">{key}</a>
              </div>
            ))}
          </Masonry>
        </div>
      </main>

      <footer className="relative h-[90px] flex justify-center align-center uppercase text-lg font-medium z-20">
        <p>Jonathan Liu Photography</p>
      </footer>
    </div>
  );
}

