"use client"

import { Tab, TabGroup, TabList, TabPanel, TabPanels } from "@headlessui/react";
import Head from "next/head";
import Link from "next/link";
import Masonry from "react-masonry-css";
import classNames from "classnames";
import Image from "next/image";

import { dic, pics } from "../_images";

export default function Page() {

  return (
    <div className="h-full overflow-auto">
      <Head>
        <title>Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="flex flex-col h-full items-center relative">
        <Masonry breakpointCols={2} className="flex gap-4 h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
          {pics.map((key) => (
            <a key={key} href={"/gallery/" + key}>
              <Image
                key={key}
                src={dic[key][0]}
                alt="thumbnail"
                className="my-4 cursor-pointer"
                placeholder="blur"
              />
            </a>
          ))}
        </Masonry>
      </div>

      <footer className="relative h-[90px] flex justify-center align-center uppercase text-lg font-medium z-20">
        <p>Placeholder for footer</p>
      </footer>
    </div>
  );
}

